language: node_js
node_js:
- '11'
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: V6qTO5KPDnvZ+I4hm5GOfmdRJVcHF3RhF+TW06J6bM9Yi8hbEVufoPguEZFyU8ayjyBQan5Yk+fQTYHODsSz/TSHdq/z0rjZ2MktIeqd0sCKYYOz6M7ReRmezRe602NHnZ9t5lzgbNYE+tNAG52BqumY3CCr2DN/0kCLmpx08rTbElDQDtVsbNQCesKsCsYkpD2xoBxe2X2a81m0gjk5YfMmY5w/mPBUQowslHKjCKNIpEfKFD43jJJesaT4/njR+fWG4pnLhBXhMd1M4EaR8ZUQd8lO7lng9gsMLfYDlRyMgUBi3FV2xJagG0EJOg3ewo2E0P3mdN6VjJe+Sq1nHG2d8iXkXs8Z1/C7JoTfOjZrNiDhw7xSxOzKKAeOWvQho/iFTsFK7EBYZJf0YSM/WWZB8IVxOPfp3luT8OIQwyQns40GloGpIu4QkWTKKO9vYCIF9XTyQc9YuEibrERQsGO/n9iDvQxHk3CEbImYeeOaedEQOo+RUwMG9JlfNEcuO0JkJv0/OFG1cdcFFkeqci+ay1mrSfRoXaw4yFPAuX1iMGSeA4nW64aA9uB+kYSt+YF8bicV7iCZ3AVVWs8aRrTr+BIjpQmt3ZjsRBXXj9qDNOG4vInRa6kLrew01dAf9knMXno4gvvVvNnSU1d2e7CXr/joQ5XHnPlQt5jQC9Y=
  app: dog-fetch
  skip_cleanup: true
scripts:
  start: node server.js
  test: NODE_ENV=test jest --exit
