language: node_js
node_js:
- '11'
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: KJkN2+cmnckSp1YqAsIINIazjtKtf7DvInpWe499jMFJSvYyQMaOrqbphLEgKi7HaRk32anBMhYjR5MX/o+rPQ9NBRVTTPh/453C+07jX4gd9T4ms/mFcW2QaJG322MwFbohiBCpDZFak9wUZ4G2WmTJ05+VafVICaYKBwJ0XiIxIDxsu9TbsIBfqZ6+ugrqube32Aj08airnV65kKY+aRiA800uP7QtwQcjyf59Pbo+A5t/yN7DLGHYyp1NJZ4ZyH1JzgC1bzUOIxmetd7ABdTet+DMmu/MiCXCVr9cju24uz5wCaCTrQmP7aUhtUWN6eZNOHm7a9WOSubPqxI3nidEsCncueTqaW6Gj/4i32/nYyDAmliXWS9D/UlM6Mof8K/PpAVg+J1ZaSZ4DZDEmnyWYMc5MrRliP0bZBWoTyV4cw0BYUlL8fGiz0eeuPoScu1T6ZYcI6gzvPt2yEN1kU2Q3iXV+VKleCfvPUu7u/Ivd/1iauUHyOws6ayFWo5khkF+CeSpnF3HLXSLS+/qodCMg6f9vj71jp8zaThkdJwFIT26uGAX0dlNoO/L3gnpIrQ7fRuWn1CM/Fu5xI0ZzYRBLDPe1VK4eKF5axsHqGykFmPVBF/WPE/4s05KFwTjWJC6M1QXYf+SzsbsqBpP9DbJ9sYYI86qzf0DHAqjR9s=
  app: dog-fetch
  on:
    repo: Cody-Price/Fetch
scripts:
  start: node server.js
  test: NODE_ENV=test jest --exit
